#!/usr/bin/env python3
# -*- coding: CP1252 -*-
#
# generated by wxGlade 1.1.1 on Thu Oct 30 19:39:37 2025
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade



class Ventana4(wx.Frame):
    def __init__(self, parent, informacion = "", subtotal1 = 0, informacion2 = "", subtotal2 = 0):
        # begin wxGlade: Ventana4.__init__
        super().__init__(parent, style = wx.DEFAULT_FRAME_STYLE)
        self.SetSize((425, 485))
        self.SetTitle("frame_3")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(243, 246, 133))

        #Variables de instancia de la Ventana 4
        self.infoTaquilla = informacion
        self.infoDulceria = informacion2
        self.subtotalTaquilla = subtotal1
        self.subtotalDulceria = subtotal2
        self.total = self.subtotalTaquilla + self.subtotalDulceria 

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_2 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./logotipo_Ticket.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_2.Add(bitmap_1, 0, 0, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Ticket")
        label_1.SetFont(wx.Font(20, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_2.Add(label_1, 0, wx.ALIGN_CENTER, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./logotipo_Ticket.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_2.Add(bitmap_2, 0, 0, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "Taquilla")
        label_2.SetFont(wx.Font(16, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        sizer_1.Add(label_2, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.lbTaquilla = wx.StaticText(self.panel_1, wx.ID_ANY, f"{self.infoTaquilla}")
        self.lbTaquilla.SetMinSize((300, 50))
        self.lbTaquilla.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        sizer_1.Add(self.lbTaquilla, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.lbSubtotalTaquilla = wx.StaticText(self.panel_1, wx.ID_ANY, f"Subtotal: ${self.subtotalTaquilla}")
        self.lbSubtotalTaquilla.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        sizer_1.Add(self.lbSubtotalTaquilla, 0, 0, 0)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Dulcería")
        label_4.SetFont(wx.Font(16, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        sizer_1.Add(label_4, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.lbDulceria = wx.StaticText(self.panel_1, wx.ID_ANY, f"{self.infoDulceria}")
        self.lbDulceria.SetMinSize((300, 50))
        self.lbDulceria.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        sizer_1.Add(self.lbDulceria, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.lbSubtotalDulceria = wx.StaticText(self.panel_1, wx.ID_ANY, f"Subtotal: ${self.subtotalDulceria}")
        self.lbSubtotalDulceria.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        sizer_1.Add(self.lbSubtotalDulceria, 0, 0, 0)

        self.lbTotal = wx.StaticText(self.panel_1, wx.ID_ANY, f"Total: ${self.total}")
        self.lbTotal.SetForegroundColour(wx.Colour(255, 0, 0))
        self.lbTotal.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        sizer_1.Add(self.lbTotal, 0, wx.ALIGN_RIGHT, 0)

        grid_sizer_3 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        self.btnCancelar = wx.Button(self.panel_1, wx.ID_ANY, "Cancelar")
        self.btnCancelar.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_3.Add(self.btnCancelar, 0, wx.ALIGN_CENTER, 0)

        self.btnFinalizar = wx.Button(self.panel_1, wx.ID_ANY, "Finalizar")
        self.btnFinalizar.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_3.Add(self.btnFinalizar, 0, wx.ALIGN_CENTER, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.btnCancelar.Bind(wx.EVT_BUTTON, self.cancelarVenta)
        self.btnFinalizar.Bind(wx.EVT_BUTTON, self.finalizarVenta)
        # end wxGlade

    def cancelarVenta(self, event):  # wxGlade: Ventana4.<event_handler>
        pregunta = wx.MessageDialog(self, "Se cancelará la venta. \n"\
        "¿Está seguro que desea cancelar la venta?","Cancelar venta", style = wx.YES_NO | wx.ICON_QUESTION)
        respuesta = pregunta.ShowModal()
        pregunta.Destroy()

        if respuesta == wx.ID_YES:
            wx.Exit()
        event.Skip()

    def finalizarVenta(self, event):  # wxGlade: Ventana4.<event_handler>
        wx.MessageBox("Gracias por su compra", "Finalizar venta", wx.OK | wx.ICON_INFORMATION)
        v2 = Ventana2(self)
        v2.Show()
        self.Hide()
        event.Skip()

# end of class Ventana4
class Ventana3(wx.Frame):
    def __init__(self, parent, informacion="", subtotal=0):
        # begin wxGlade: Ventana3.__init__
        super().__init__(parent, style = wx.DEFAULT_FRAME_STYLE)
        self.SetSize((918, 590))
        self.SetTitle("frame_2")
        self.SetBackgroundColour(wx.Colour(243, 246, 133))
        print(f"Datos de la ventana 2:\nInformación: {informacion}\n")
        print(f"Subtotal: {subtotal}")
        

        self.subtotalDulceria = 0
        self.infoDulceria = ""
        self.infoTaquilla = informacion
        self.subtotalTaquilla = subtotal

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_1 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        bmDulceriaLogo = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./Imagenes/logotipo ducleria.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bmDulceriaLogo, 0, 0, 0)

        lbDulceria = wx.StaticText(self.panel_1, wx.ID_ANY, "Dulceria")
        lbDulceria.SetMinSize((100, 25))
        lbDulceria.SetFont(wx.Font(16, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Verdana"))
        grid_sizer_1.Add(lbDulceria, 0, wx.ALIGN_CENTER, 0)

        bmDulceriaLogo2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./Imagenes/logotipo ducleria.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bmDulceriaLogo2, 0, wx.ALIGN_RIGHT, 0)

        grid_sizer_2 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        grid_sizer_3 = wx.FlexGridSizer(1, 3, 0, 0)
        grid_sizer_2.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        self.spComboB = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_3.Add(self.spComboB, 0, 0, 0)

        grid_sizer_5 = wx.FlexGridSizer(2, 1, 0, 0)
        grid_sizer_3.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        lbBasico = wx.StaticText(self.panel_1, wx.ID_ANY, u"Básico $75")
        lbBasico.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Verdana"))
        grid_sizer_5.Add(lbBasico, 0, 0, 0)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas ch\nrefresco ch\n", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_4.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_5.Add(label_4, 0, 0, 0)

        bmComboBasico = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./Imagenes/combo1.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_3.Add(bmComboBasico, 0, 0, 0)

        grid_sizer_4 = wx.FlexGridSizer(1, 3, 0, 0)
        grid_sizer_2.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        self.spComboC = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_4.Add(self.spComboC, 0, 0, 0)

        grid_sizer_6 = wx.FlexGridSizer(2, 1, 0, 0)
        grid_sizer_4.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        scComboCuates = wx.StaticText(self.panel_1, wx.ID_ANY, "Cuates $130")
        scComboCuates.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Verdana"))
        grid_sizer_6.Add(scComboCuates, 0, 0, 0)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas md\n2 refrescos md", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_5.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_6.Add(label_5, 0, 0, 0)

        bitmap_4 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./Imagenes/combo2.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_4.Add(bitmap_4, 0, 0, 0)

        grid_sizer_7 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_7, 1, wx.EXPAND, 0)

        grid_sizer_8 = wx.FlexGridSizer(1, 3, 0, 0)
        grid_sizer_7.Add(grid_sizer_8, 1, wx.EXPAND, 0)

        self.spComboF = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_8.Add(self.spComboF, 0, 0, 0)

        grid_sizer_9 = wx.FlexGridSizer(2, 1, 0, 0)
        grid_sizer_8.Add(grid_sizer_9, 1, wx.EXPAND, 0)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, "Familiar $200")
        label_6.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Verdana"))
        grid_sizer_9.Add(label_6, 0, 0, 0)

        label_7 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas g\n3 refrescos g\n1 dulce")
        label_7.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_9.Add(label_7, 0, 0, 0)

        bitmap_7 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./Imagenes/combo3.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_8.Add(bitmap_7, 0, 0, 0)

        grid_sizer_7.Add((0, 0), 0, 0, 0)

        grid_sizer_10 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_10, 1, wx.EXPAND, 0)

        grid_sizer_11 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_10.Add(grid_sizer_11, 1, wx.EXPAND, 0)

        bitmap_5 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./Imagenes/palomitas2(ch).png", wx.BITMAP_TYPE_ANY))
        grid_sizer_11.Add(bitmap_5, 0, 0, 0)

        grid_sizer_12 = wx.GridSizer(2, 1, 0, 0)
        grid_sizer_11.Add(grid_sizer_12, 1, wx.EXPAND, 0)

        label_8 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas")
        label_8.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Verdana"))
        grid_sizer_12.Add(label_8, 0, 0, 0)

        grid_sizer_13 = wx.FlexGridSizer(3, 2, 0, 0)
        grid_sizer_12.Add(grid_sizer_13, 1, wx.EXPAND, 0)

        self.spPalomitasCh = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_13.Add(self.spPalomitasCh, 0, 0, 0)

        label_13 = wx.StaticText(self.panel_1, wx.ID_ANY, "Chicas")
        label_13.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_13.Add(label_13, 0, 0, 0)

        self.spPalomitasMd = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_13.Add(self.spPalomitasMd, 0, 0, 0)

        label_14 = wx.StaticText(self.panel_1, wx.ID_ANY, "Medianas")
        label_14.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_13.Add(label_14, 0, 0, 0)

        self.spPalomitasG = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_13.Add(self.spPalomitasG, 0, 0, 0)

        label_15 = wx.StaticText(self.panel_1, wx.ID_ANY, "Grandes")
        label_15.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_13.Add(label_15, 0, 0, 0)

        grid_sizer_15 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_10.Add(grid_sizer_15, 1, wx.EXPAND, 0)

        bitmap_6 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./Imagenes/refresco(m).png", wx.BITMAP_TYPE_ANY))
        grid_sizer_15.Add(bitmap_6, 0, 0, 0)

        grid_sizer_16 = wx.FlexGridSizer(2, 1, 0, 0)
        grid_sizer_15.Add(grid_sizer_16, 1, wx.EXPAND, 0)

        label_9 = wx.StaticText(self.panel_1, wx.ID_ANY, "Refrescos")
        label_9.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Verdana"))
        grid_sizer_16.Add(label_9, 0, 0, 0)

        grid_sizer_17 = wx.GridSizer(2, 3, 0, 0)
        grid_sizer_16.Add(grid_sizer_17, 1, wx.EXPAND, 0)

        label_10 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Tamaño")
        label_10.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_17.Add(label_10, 0, 0, 0)

        label_11 = wx.StaticText(self.panel_1, wx.ID_ANY, "Sabor")
        label_11.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_17.Add(label_11, 0, 0, 0)

        label_12 = wx.StaticText(self.panel_1, wx.ID_ANY, "Cantidad")
        label_12.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_17.Add(label_12, 0, 0, 0)

        self.cmbTamano = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["Chico", "Mediano", "Grande"], style=wx.CB_DROPDOWN)
        grid_sizer_17.Add(self.cmbTamano, 0, 0, 0)

        self.cmbSabor = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["Cola", "Sprite", "Manzana"], style=wx.CB_DROPDOWN)
        grid_sizer_17.Add(self.cmbSabor, 0, 0, 0)

        grid_sizer_18 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_17.Add(grid_sizer_18, 1, wx.EXPAND, 0)

        self.spCantidad = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_18.Add(self.spCantidad, 0, 0, 0)

        self.btnAgregar = wx.Button(self.panel_1, wx.ID_ANY, "Agregar")
        self.btnAgregar.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_18.Add(self.btnAgregar, 0, 0, 0)

        grid_sizer_20 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_20, 1, wx.EXPAND, 0)

        grid_sizer_23 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_20.Add(grid_sizer_23, 1, wx.EXPAND, 0)

        label_18 = wx.StaticText(self.panel_1, wx.ID_ANY, "Productos agredos:")
        label_18.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Verdana"))
        grid_sizer_23.Add(label_18, 0, 0, 0)

        self.lbProductosAgregados = wx.StaticText(self.panel_1, wx.ID_ANY, "...")
        grid_sizer_23.Add(self.lbProductosAgregados, 0, 0, 0)

        grid_sizer_22 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_20.Add(grid_sizer_22, 1, wx.EXPAND, 0)

        f = wx.StaticText(self.panel_1, wx.ID_ANY, u"Subtotal Dulcería:")
        f.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Verdana"))
        grid_sizer_22.Add(f, 0, 0, 0)

        self.lbSubtotal = wx.StaticText(self.panel_1, wx.ID_ANY, "$00.00")
        grid_sizer_22.Add(self.lbSubtotal, 0, 0, 0)

        grid_sizer_19 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_19, 1, wx.EXPAND, 0)

        self.btnLimpiar = wx.Button(self.panel_1, wx.ID_ANY, "Limpiar")
        self.btnLimpiar.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Verdana"))
        grid_sizer_19.Add(self.btnLimpiar, 0, wx.ALIGN_CENTER, 0)

        self.btnSiguiente = wx.Button(self.panel_1, wx.ID_ANY, "Siguiente")
        self.btnSiguiente.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Verdana"))
        grid_sizer_19.Add(self.btnSiguiente, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_9.AddGrowableRow(0)
        grid_sizer_9.AddGrowableCol(0)

        grid_sizer_8.AddGrowableRow(0)
        grid_sizer_8.AddGrowableCol(1)

        grid_sizer_6.AddGrowableRow(0)
        grid_sizer_6.AddGrowableRow(1)
        grid_sizer_6.AddGrowableCol(0)

        grid_sizer_4.AddGrowableRow(0)
        grid_sizer_4.AddGrowableCol(1)

        grid_sizer_5.AddGrowableRow(0)
        grid_sizer_5.AddGrowableRow(1)
        grid_sizer_5.AddGrowableCol(0)

        grid_sizer_3.AddGrowableRow(0)
        grid_sizer_3.AddGrowableCol(1)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.spComboB.Bind(wx.EVT_SPINCTRL, self.calcularComboBasico)
        self.spComboC.Bind(wx.EVT_SPINCTRL, self.calcularComboCuates)
        self.spComboF.Bind(wx.EVT_SPINCTRL, self.calcularComboFamiliar)
        self.spPalomitasCh.Bind(wx.EVT_SPINCTRL, self.calcularPalomitasCh)
        self.spPalomitasMd.Bind(wx.EVT_SPINCTRL, self.calcularPalomitasMd)
        self.spPalomitasG.Bind(wx.EVT_SPINCTRL, self.calcularPalomitasG)
        self.btnAgregar.Bind(wx.EVT_BUTTON, self.agregarRefresco)
        self.btnLimpiar.Bind(wx.EVT_BUTTON, self.limpiarDulceria)
        self.btnSiguiente.Bind(wx.EVT_BUTTON, self.siguienteDulceria)
        # end wxGlade

    def calcularComboBasico(self, event):  # wxGlade: Ventana3.<event_handler>
        numero = int(self.spComboB.GetValue())
        subtotal_combo = numero * 75

        self.subtotalDulceria = self.subtotalDulceria + subtotal_combo
        self.infoDulceria = self.infoDulceria + f"{numero} Combos Básicos \n"

        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")
        
        event.Skip()
    
    def calcularComboCuates(self, event):  # wxGlade: Ventana3.<event_handler>
        numero = int(self.spComboC.GetValue())
        subtotal_combo = numero * 130

        self.subtotalDulceria = self.subtotalDulceria + subtotal_combo
        self.infoDulceria = self.infoDulceria + f"{numero} Combos Cuates \n"

        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")

        event.Skip()
    
    def calcularComboFamiliar(self, event):  # wxGlade: Ventana3.<event_handler>
        numero = int(self.spComboF.GetValue())
        subtotal_combo = numero * 200

        self.subtotalDulceria = self.subtotalDulceria + subtotal_combo
        self.infoDulceria = self.infoDulceria + f"{numero} Combos Familiares \n"

        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")

        event.Skip()
    
    def calcularPalomitasCh(self, event):  # wxGlade: Ventana3.<event_handler>
        numero = int(self.spPalomitasCh.GetValue())
        subtotal_palomitas = numero * 30

        self.subtotalDulceria = self.subtotalDulceria + subtotal_palomitas
        self.infoDulceria = self.infoDulceria + f"{numero} Palomitas Chicas \n"

        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")

        event.Skip()
    
    def calcularPalomitasMd(self, event):  # wxGlade: Ventana3.<event_handler>
        numero = int(self.spPalomitasMd.GetValue())
        subtotal_palomitas = numero * 50

        self.subtotalDulceria = self.subtotalDulceria + subtotal_palomitas
        self.infoDulceria = self.infoDulceria + f"{numero} Palomitas Medianas \n"

        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")

        event.Skip()
    
    def calcularPalomitasG(self, event):  # wxGlade: Ventana3.<event_handler>
        numero = int(self.spPalomitasG.GetValue())
        subtotal_palomitas = numero * 70

        self.subtotalDulceria = self.subtotalDulceria + subtotal_palomitas
        self.infoDulceria = self.infoDulceria + f"{numero} Palomitas Grandes \n"

        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")

        event.Skip()
    
    def agregarRefresco(self, event):  # wxGlade: Ventana3.<event_handler>
        tamano = self.cmbTamano.GetValue()
        sabor = self.cmbSabor.GetValue()
        cantidad = int(self.spCantidad.GetValue())

        if tamano == "Chico":
            subtotal_refrescos = cantidad * 25

        elif tamano == "Mediano":
            subtotal_refrescos = cantidad * 40

        elif tamano == "Grande":
            subtotal_refrescos = cantidad * 60

        self.subtotalDulceria = self.subtotalDulceria + subtotal_refrescos
        self.infoDulceria = self.infoDulceria + f"{cantidad} Refresco: {sabor} Tamaño{tamano} \n" 
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")
        
        event.Skip()
    
    def limpiarD(self):
        self.subtotalDulceria = 0
        self.infoDulceria = ""

        self.spComboB.SetValue(0)
        self.spComboC.SetValue(0)
        self.spComboF.SetValue(0)
        self.spPalomitasCh.SetValue(0)
        self.spPalomitasMd.SetValue(0)
        self.spPalomitasG.SetValue(0)
        self.spCantidad.SetValue(0)
        self.cmbSabor.SetSelection(wx.NOT_FOUND)
        self.cmbTamano.SetSelection(wx.NOT_FOUND)
        self.lbProductosAgregados.SetLabel("---")
        self.lbSubtotal.SetLabel("$00.00")
    
    def limpiarDulceria(self, event):  # wxGlade: Ventana3.<event_handler>
        self.limpiarD()
        event.Skip()
    
    def siguienteDulceria(self, event):  # wxGlade: Ventana3.<event_handler>
        pregunta = wx.MessageDialog(self,
            f"Confirmación de Dulcería.\n"
            f"¿Está seguro que desea adquirir?\n\n{self.infoDulceria}\n"
            f"Subtotal Dulcería: ${self.subtotalDulceria}",
            "Dulcería", style = wx.YES_NO | wx.ICON_QUESTION)
        
        respuesta = pregunta.ShowModal()
        pregunta.Destroy()

        if respuesta == wx.ID_YES:
            v4 = Ventana4(self, informacion = self.infoTaquilla, subtotal1 = self.subtotalTaquilla, 
                         informacion2 = self.infoDulceria, subtotal2 = self.subtotalDulceria)
            v4.Show()
            self.limpiarD()
            self.Hide()
        elif respuesta == wx.ID_NO:
            self.limpiarD()
        event.Skip()

# end of class Ventana3

class Ventana2(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Ventana2.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 534))
        self.SetTitle("frame_1")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetMinSize((384, 495))
        self.panel_1.SetBackgroundColour(wx.Colour(243, 246, 133))

        self.subtotal = 0
        self.adultos = 0
        self.menores = 0
        self.informacion = ""
        self.horarioSeleccionado = ""

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_1 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        bmlogopeli1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("D:\\cineplusLeonel3A\\logotipo peliculas.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bmlogopeli1, 0, 0, 0)

        lbTaquilla = wx.StaticText(self.panel_1, wx.ID_ANY, "Taquilla")
        lbTaquilla.SetMinSize((93, 30))
        lbTaquilla.SetFont(wx.Font(16, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Verdana"))
        grid_sizer_1.Add(lbTaquilla, 0, wx.ALIGN_CENTER | wx.RIGHT | wx.TOP, 0)

        bmlogopeli2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("D:\\cineplusLeonel3A\\logotipo peliculas.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bmlogopeli2, 0, wx.ALIGN_RIGHT, 0)

        grid_sizer_2 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        lbPelicula = wx.StaticText(self.panel_1, wx.ID_ANY, u"Película:")
        lbPelicula.SetMinSize((70, 30))
        lbPelicula.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_2.Add(lbPelicula, 0, wx.ALIGN_CENTER, 0)

        self.cmbPeliculas = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["Spider-man", "Vengadores", "Terror bajo la tierra"], style=wx.CB_DROPDOWN)
        grid_sizer_2.Add(self.cmbPeliculas, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.bmPelicula = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("D:\\cineplusLeonel3A\\spiderman.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_2.Add(self.bmPelicula, 0, 0, 0)

        grid_sizer_3 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        labSala = wx.StaticText(self.panel_1, wx.ID_ANY, "Sala:")
        labSala.SetMinSize((40, 21))
        labSala.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_3.Add(labSala, 0, wx.ALIGN_CENTER, 0)

        self.lbSala = wx.StaticText(self.panel_1, wx.ID_ANY, "...")
        grid_sizer_3.Add(self.lbSala, 0, 0, 0)

        grid_sizer_5 = wx.GridSizer(2, 3, 0, 0)
        sizer_1.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        lbHorario = wx.StaticText(self.panel_1, wx.ID_ANY, "Horario:")
        lbHorario.SetMinSize((65, 19))
        lbHorario.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_5.Add(lbHorario, 0, wx.ALIGN_CENTER, 0)

        self.rbHorario1 = wx.RadioButton(self.panel_1, wx.ID_ANY, "00:00\n")
        self.rbHorario1.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_5.Add(self.rbHorario1, 0, wx.ALIGN_CENTER, 0)

        self.rbHorario2 = wx.RadioButton(self.panel_1, wx.ID_ANY, "00:00")
        self.rbHorario2.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_5.Add(self.rbHorario2, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_5.Add((0, 0), 0, 0, 0)

        self.rbHorario3 = wx.RadioButton(self.panel_1, wx.ID_ANY, "00:00")
        self.rbHorario3.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_5.Add(self.rbHorario3, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_5.Add((0, 0), 0, 0, 0)

        lbBoletos = wx.StaticText(self.panel_1, wx.ID_ANY, "Boletos")
        lbBoletos.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        sizer_1.Add(lbBoletos, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_7 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_7, 1, wx.EXPAND, 0)

        lbAdultos = wx.StaticText(self.panel_1, wx.ID_ANY, "Adultos ($80)")
        lbAdultos.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_7.Add(lbAdultos, 0, wx.ALIGN_CENTER, 0)

        self.tfAdultos = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_PROCESS_ENTER)
        grid_sizer_7.Add(self.tfAdultos, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        grid_sizer_8 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_8, 1, wx.EXPAND, 0)

        lbMenores = wx.StaticText(self.panel_1, wx.ID_ANY, "Menores ($80)")
        lbMenores.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_8.Add(lbMenores, 0, wx.ALIGN_CENTER, 0)

        self.tfMenores = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_PROCESS_ENTER)
        grid_sizer_8.Add(self.tfMenores, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        grid_sizer_9 = wx.GridSizer(1, 1, 0, 0)
        sizer_1.Add(grid_sizer_9, 1, wx.EXPAND, 0)

        self.lbSubtotal = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal:")
        self.lbSubtotal.SetMinSize((70, 19))
        self.lbSubtotal.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Verdana"))
        grid_sizer_9.Add(self.lbSubtotal, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        grid_sizer_6 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        self.btnLimpiar = wx.Button(self.panel_1, wx.ID_ANY, "Limpiar")
        self.btnLimpiar.SetMinSize((75, 23))
        self.btnLimpiar.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        grid_sizer_6.Add(self.btnLimpiar, 0, wx.ALIGN_CENTER, 0)

        self.btnSiguiente = wx.Button(self.panel_1, wx.ID_ANY, "Siguiente")
        self.btnSiguiente.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        grid_sizer_6.Add(self.btnSiguiente, 0, wx.ALIGN_CENTER, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.cmbPeliculas.Bind(wx.EVT_COMBOBOX, self.seleccionPelicula)
        self.rbHorario1.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario1)
        self.rbHorario2.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario2)
        self.rbHorario3.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario3)
        self.tfAdultos.Bind(wx.EVT_TEXT_ENTER, self.sumarAdultos)
        self.tfMenores.Bind(wx.EVT_TEXT_ENTER, self.sumarMenores)
        self.btnLimpiar.Bind(wx.EVT_BUTTON, self.limpiarTaquilla)
        self.btnSiguiente.Bind(wx.EVT_BUTTON, self.siguienteVentana)
        # end wxGlade

    def cargar_imagen(self, ruta):
        bitmap = wx.Bitmap(ruta, wx.BITMAP_TYPE_ANY)
        self.bmPelicula.SetBitmap(bitmap)

    def seleccionPelicula(self, event):  # wxGlade: Ventana2.<event_handler>
        pelicula = self.cmbPeliculas.GetValue()
        imagen = ""
        sala = ""
        horario1 = horario2 = horario3 = ""

        print(f"Pelicula seleccionada: {pelicula}")

        if pelicula == "Spider-man":
            imagen = "spiderman.png"
            sala = "1"
            horario1 = "14:00"
            horario2 = "17:00"
            horario3 = "20:00"

        elif pelicula == "Vengadores":
            imagen = "vengadores.png"
            sala = "2"
            horario1 = "13:30"
            horario2 = "16:30"
            horario3 = "19:30"

        elif pelicula == "Terror bajo la tierra":
            imagen = "tblt.png"
            sala = "3"
            horario1 = "15:00"
            horario2 = "18:00"
            horario3 = "21:00"
        
        self.cargar_imagen(imagen)
        self.lbSala.SetLabel(sala)
        self.rbHorario1.SetLabel(horario1)
        self.rbHorario2.SetLabel(horario2)
        self.rbHorario3.SetLabel(horario3)
        self.informacion = f"Pelicula: {pelicula} \n Sala: {sala}"
        print(f"Listo para disfrutar de \n {self.informacion}")
        event.Skip()

    def seleccionHorario1(self, event):  # wxGlade: Ventana2.<event_handler>
        self.horarioSeleccionado = self.rbHorario1.GetLabelText()
        event.Skip()

    def seleccionHorario2(self, event):  # wxGlade: Ventana2.<event_handler>
        self.horarioSeleccionado = self.rbHorario2.GetLabelText()
        event.Skip()

    def seleccionHorario3(self, event):  # wxGlade: Ventana2.<event_handler>
        self.horarioSeleccionado = self.rbHorario3.GetLabelText()
        event.Skip()

    def sumarAdultos(self, event):  # wxGlade: Ventana2.<event_handler>
        try:
            self.adultos = int(self.tfAdultos.GetValue())
            subtotal_a = self.adultos * 80
            self.subtotal = subtotal_a
            self.lbSubtotal.SetLabel(f"Subtotal: ${subtotal_a:.2f}")

        except ValueError:
            wx.MessageBox("Por favor ingresa un número válido", "Error", wx.OK | wx.ICON_ERROR)
        event.Skip()

    def sumarMenores(self, event):  # wxGlade: Ventana2.<event_handler>
        try:
            self.menores = int(self.tfMenores.GetValue())
            subtotal_b = self.menores * 70
            self.subtotal = (self.adultos * 80) + subtotal_b
            self.lbSubtotal.SetLabel(f"Subtotal: ${self.subtotal:.2f}")

        except ValueError:
            wx.MessageBox("Por favor ingresa un número válido", "Error", wx.OK | wx.ICON_ERROR)
    
        event.Skip()

    def limpiarValores_Campos(self):

        self.subtotal = 0
        self.adultos = 0
        self.menores = 0
        self.informacion = ""
        self.horarioSeleccionado = ""

        self.cargar_imagen("logotipo.png")
        self.rbHorario1.SetLabel("00:00")
        self.rbHorario2.SetLabel("00:00")
        self.rbHorario3.SetLabel("00:00")
        self.rbHorario1.SetValue(False)
        self.rbHorario2.SetValue(False)
        self.rbHorario3.SetValue(False)
        self.cmbPeliculas.SetSelection(wx.NOT_FOUND)
        self.lbSala.SetLabel("---")
        self.tfAdultos.SetValue("0")
        self.tfMenores.SetValue("0")
        self.lbSubtotal.SetLabel("0")

    def limpiarTaquilla(self, event):  # wxGlade: Ventana2.<event_handler>
        self.limpiarValores_Campos()
        event.Skip()

    def siguienteVentana(self, event):  # wxGlade: Ventana2.<event_handler>
        self.informacion = f"{self.informacion} \n Horario: {self.horarioSeleccionado}"
        self.informacion = f"{self.informacion} \n Adultos: {self.adultos} \n Adultos: {self.menores}"
        self.informacion = f"{self.informacion} \n Subtotal: {self.subtotal}"

        pregunta = wx.MessageDialog(
            self,
            f"Confirmación de Taquilla.\n"
            f"¿Está seguro que desea  adquirir?\n\n{self.informacion}",
            "Taquilla",
            style = wx.YES_NO | wx.ICON_QUESTION
        )

        respuesta = pregunta.ShowModal()
        pregunta.Destroy()

        if respuesta == wx.ID_YES:
            print(f"Ventana de Taquilla realizada\n {self.informacion}")
            v3 = Ventana3(self, informacion = self.informacion, subtotal = self.subtotal)
            v3.Show()
            self.limpiarValores_Campos()
            self.Hide()
        
        elif respuesta == wx.ID_NO:
            self.limpiarValores_Campos()
        event.Skip()

# end of class Ventana2

class Ventana1(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Ventana1.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((411, 454))
        self.SetTitle(u"Inicio de sesión - CinePlus")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("D:\\cineplusLeonel3A\\logotipo.png", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetMinSize((345, 231))
        self.panel_1.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.panel_1.SetForegroundColour(wx.Colour(255, 255, 255))
        self.panel_1.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        lbtitulo = wx.StaticText(self.panel_1, wx.ID_ANY, "\"Bienvenido a CinePlus\"", style=wx.ALIGN_CENTER_HORIZONTAL)
        lbtitulo.SetMinSize((132, 35))
        lbtitulo.SetForegroundColour(wx.Colour(255, 255, 255))
        lbtitulo.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(lbtitulo, 0, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./Imagenes/logotipo.png", wx.BITMAP_TYPE_ANY))
        sizer_1.Add(bitmap_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        lbUsuario = wx.StaticText(self.panel_1, wx.ID_ANY, "Usuario:", style=wx.ALIGN_CENTER_HORIZONTAL)
        lbUsuario.SetBackgroundColour(wx.Colour(3, 3, 3))
        lbUsuario.SetForegroundColour(wx.Colour(255, 255, 255))
        lbUsuario.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_1.Add(lbUsuario, 0, wx.EXPAND, 0)

        self.tfUsuario = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.tfUsuario.SetMinSize((200, 27))
        self.tfUsuario.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Narrow"))
        sizer_1.Add(self.tfUsuario, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        lbContrasenna = wx.StaticText(self.panel_1, wx.ID_ANY, u"Contraseña:", style=wx.ALIGN_CENTER_HORIZONTAL)
        lbContrasenna.SetBackgroundColour(wx.Colour(0, 0, 0))
        lbContrasenna.SetForegroundColour(wx.Colour(255, 255, 255))
        lbContrasenna.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(lbContrasenna, 0, wx.EXPAND, 0)

        self.tfClave = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_PASSWORD)
        self.tfClave.SetMinSize((200, 27))
        self.tfClave.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Narrow"))
        sizer_1.Add(self.tfClave, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.btnEntrar = wx.Button(self.panel_1, wx.ID_ANY, "Entrar")
        self.btnEntrar.SetMinSize((120, 35))
        self.btnEntrar.SetBackgroundColour(wx.Colour(50, 153, 204))
        sizer_1.Add(self.btnEntrar, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.btnSalir = wx.Button(self.panel_1, wx.ID_ANY, "Salir")
        self.btnSalir.SetMinSize((120, 35))
        self.btnSalir.SetBackgroundColour(wx.Colour(165, 42, 42))
        sizer_1.Add(self.btnSalir, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.btnEntrar.Bind(wx.EVT_BUTTON, self.confirmar_usuario_clave)
        self.btnSalir.Bind(wx.EVT_BUTTON, self.cerrar_programa)
        # end wxGlade

    def confirmar_usuario_clave(self, event):  # wxGlade: Ventana1.<event_handler>
        nombre = self.tfUsuario.GetValue()
        clave = self.tfClave.GetValue()

        if nombre == "Leos" and clave=="123456":
            print(f"¡Bienvenido, {nombre}! Acceso autorizado.")
            v2 = Ventana2(self)
            v2.Show()
            self.Hide()
        else:
            print("Acceso denegado. Usuario o clave incorrectos.")
        event.Skip()

    def cerrar_programa(self, event):  # wxGlade: Ventana1.<event_handler>
        pregunta = wx.MessageDialog(self, "Se cerrará la ventana. \n"\
        "¿Está seguro que desea salir?","Confirmar salida", style = wx.YES_NO | wx.ICON_QUESTION)
        respuesta = pregunta.ShowModal()
        pregunta.Destroy()

        if respuesta == wx.ID_YES:
            print("Bye¡")
            self.Close()
        event.Skip()

# end of class Ventana1

class MyAppCineplus(wx.App):
    def OnInit(self):
        self.frame_2 = Ventana1(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame_2)
        self.frame_2.Show()
        return True

# end of class MyAppCineplus

if __name__ == "__main__":
    appCineplus = MyAppCineplus(0)
    appCineplus.MainLoop()
