#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Tue Oct  7 08:42:55 2025
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class ventana1(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ventana1.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((411, 454))
        self.SetTitle(u"Inicio de sesión - CinePlus")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("E:\\cineplusLeonel3A\\logotipo.png", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetMinSize((345, 231))
        self.panel_1.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.panel_1.SetForegroundColour(wx.Colour(255, 255, 255))
        self.panel_1.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        lbtitulo = wx.StaticText(self.panel_1, wx.ID_ANY, "\"Bienvenido a CinePlus\"", style=wx.ALIGN_CENTER_HORIZONTAL)
        lbtitulo.SetMinSize((132, 35))
        lbtitulo.SetForegroundColour(wx.Colour(255, 255, 255))
        lbtitulo.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(lbtitulo, 0, wx.EXPAND, 0)

        lbLogo = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./logotipo.png", wx.BITMAP_TYPE_ANY))
        sizer_1.Add(lbLogo, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        lbUsuario = wx.StaticText(self.panel_1, wx.ID_ANY, "Usuario:", style=wx.ALIGN_CENTER_HORIZONTAL)
        lbUsuario.SetBackgroundColour(wx.Colour(3, 3, 3))
        lbUsuario.SetForegroundColour(wx.Colour(255, 255, 255))
        lbUsuario.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_1.Add(lbUsuario, 0, wx.EXPAND, 0)

        self.tfUsuario = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.tfUsuario.SetMinSize((200, 27))
        self.tfUsuario.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Narrow"))
        sizer_1.Add(self.tfUsuario, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        lbContrasenna = wx.StaticText(self.panel_1, wx.ID_ANY, u"Contraseña:", style=wx.ALIGN_CENTER_HORIZONTAL)
        lbContrasenna.SetBackgroundColour(wx.Colour(0, 0, 0))
        lbContrasenna.SetForegroundColour(wx.Colour(255, 255, 255))
        lbContrasenna.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(lbContrasenna, 0, wx.EXPAND, 0)

        self.text_ctrl_1 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_PASSWORD)
        self.text_ctrl_1.SetMinSize((200, 27))
        self.text_ctrl_1.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Narrow"))
        sizer_1.Add(self.text_ctrl_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.btnEntrar = wx.Button(self.panel_1, wx.ID_ANY, "Entrar")
        self.btnEntrar.SetMinSize((120, 35))
        self.btnEntrar.SetBackgroundColour(wx.Colour(50, 153, 204))
        sizer_1.Add(self.btnEntrar, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.btnSalir = wx.Button(self.panel_1, wx.ID_ANY, "Salir")
        self.btnSalir.SetMinSize((120, 35))
        self.btnSalir.SetBackgroundColour(wx.Colour(165, 42, 42))
        sizer_1.Add(self.btnSalir, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.btnEntrar.Bind(wx.EVT_BUTTON, self.confirmar_usuario_clave)
        self.btnSalir.Bind(wx.EVT_BUTTON, self.cerrar_programa)
        # end wxGlade

    def confirmar_usuario_clave(self, event):  # wxGlade: ventana1.<event_handler>
        print("Event handler 'confirmar_usuario_clave' not implemented!")
        event.Skip()

    def cerrar_programa(self, event):  # wxGlade: ventana1.<event_handler>
        print("Event handler 'cerrar_programa' not implemented!")
        event.Skip()

# end of class ventana1

class MyAppCineplus(wx.App):
    def OnInit(self):
        self.frame = ventana1(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyAppCineplus

if __name__ == "__main__":
    appCineplus = MyAppCineplus(0)
    appCineplus.MainLoop()
